cp data_structures/Dp*.m abstract_factory/lab
cp data_structures/Dp*.m abstract_factory/solution
cp data_structures/Dp*.m adapter/lab
cp data_structures/Dp*.m adapter/solution
cp data_structures/Dp*.m bridge/lab
cp data_structures/Dp*.m bridge/solution
cp data_structures/Dp*.m bridge/factory_solution
cp data_structures/Dp*.m builder/lab
cp data_structures/Dp*.m builder/solution
cp data_structures/Dp*.m chain_of_responsibility/lab
cp data_structures/Dp*.m chain_of_responsibility/solution
cp data_structures/Dp*.m clone/lab
cp data_structures/Dp*.m clone/solution
cp data_structures/Dp*.m command/lab
cp data_structures/Dp*.m command/solution
cp data_structures/Dp*.m command/memento_solution
cp data_structures/Dp*.m composite/lab
cp data_structures/Dp*.m composite/solution
cp data_structures/Dp*.m decorator/lab
cp data_structures/Dp*.m decorator/solution
cp data_structures/Dp*.m facade/lab
cp data_structures/Dp*.m facade/solution
cp data_structures/Dp*.m factory_method/lab
cp data_structures/Dp*.m factory_method/solution
cp data_structures/Dp*.m flyweight/lab
cp data_structures/Dp*.m flyweight/solution
cp data_structures/Dp*.m interpreter/lab
cp data_structures/Dp*.m interpreter/solution
cp data_structures/Dp*.m iterator/lab
cp data_structures/Dp*.m iterator/solution
cp data_structures/Dp*.m mediator/lab
cp data_structures/Dp*.m mediator/solution
cp data_structures/Dp*.m memento/lab
cp data_structures/Dp*.m memento/solution
cp data_structures/Dp*.m null_object/lab
cp data_structures/Dp*.m null_object/solution
cp data_structures/Dp*.m observer/lab
cp data_structures/Dp*.m observer/solution
cp data_structures/Dp*.m prototype/lab
cp data_structures/Dp*.m prototype/solution
cp data_structures/Dp*.m proxy/lab
cp data_structures/Dp*.m proxy/solution
cp data_structures/Dp*.m singleton/abstract_factory/lab
cp data_structures/Dp*.m singleton/abstract_factory/solution
cp data_structures/Dp*.m singleton/flyweight/lab
cp data_structures/Dp*.m singleton/flyweight/solution
cp data_structures/Dp*.m state/lab
cp data_structures/Dp*.m state/solution
cp data_structures/Dp*.m strategy/lab
cp data_structures/Dp*.m strategy/solution
cp data_structures/Dp*.m template_method/lab
cp data_structures/Dp*.m template_method/solution
cp data_structures/Dp*.m visitor/lab
cp data_structures/Dp*.m visitor/solution
